config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者ログイン画面
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
  # ユーザーログイン・新規登録画面
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ルートパス設定
  root to: "public/homes#top"

  # ゲストログイン
  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー画面のルーティング設定
  scope module: :public do
    # Homesコントローラ
    get "/about" => "homes#about", as: "about"

    # Recruitsコントローラ

    resources :recruits do
      # , :except => :destroy do
      patch "update_status" => "recruits#update_status", as: "update_status"
      # Likesコントローラ
      resource :likes, only: [:create, :destroy]
    end

    # Usersコントローラ
    # get "users/:id/edit" => "users#edit", as: "edit_user"
    # get "users/:id" => "users#show", as: "show_user"
    # patch "users/:id" => "users#update", as: "update_user"
    resources :users, only: [:edit, :show, :update] do
      get "my_page" => "users#my_page", as: "my_page"
      get "unsubscribe" => "users#unsubscribe_confirm", as: "unsubscribe_confirm"
      patch "unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      # Followsコントローラ
      resource :follows, only: [:create, :destroy]
    end

    # Entriesコントローラ
    resources :entries, only: [:index, :create, :show, :destroy, :update]

    # Notifiesコントローラ
    resources :notifies, only: :index

    # Sitesコントローラ
    resources :sites, only: [:index, :create, :destroy]

    # Messagesコントローラ
    resources :messages, only: :create

    # Roomsコントローラ
    resources :rooms, only: [:show, :create]
  end

  # 管理者画面のルーティング設定
  namespace :admin do
    # Homesコントローラ
    get "/" => "homes#top"

    # Genresコントローラ
    # get "/genres" => "genres#index"
    # post "/genres" => "genres#create"
    # get "/genres/:id/edit" => "genres#edit", as: "edit_genres"
    # patch "/genres/:id" =>"genres#update", as: "update_genres"
    resources :genres, only: [:index, :create, :edit, :update]

    # Uersコンロローラ
    # get "users/:id" => "users#show", as: "show_users"
    # get "users/:id/edit" => "users#edit", as: "edit_users"
    # patch "users/:id" => "users#update", as: "update_users"
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_many :users
  has_one_attached :genre_image

  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
# frozen_string_literal: true

class Admin::GenresController < ApplicationController
  before_action :admin_only

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private
    def genre_params
      params.require(:genre).permit(
        :name,
        :genre_image
      )
    end
end

app/views/admin/genres/edit.html.erb
<div class ="container">
  
  <h3>
    ジャンル編集
  </h3>
  
  <!--START ジャンル情報編集フォーム-->
  <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
    <div class = "row g-3 mt-4 mx-auto">
      
      <!--ジャンル名入力-->
      <div class ="col-lg-10 col-md-12 col-sm-12 col-12 mt-1">
        <%= f.text_field :name, 
          placeholder:"ジャンル名", 
          class:"form-control" 
        %>
      </div>
      
      <!--ジャンル画像添付-->
      <div class="col-lg-5 col-md-6 col-sm-12 col-12 mt-1">
        <%= f.file_field :genre_image %>
      </div>
      
      <!--更新ボタン-->
      <div class="col-lg-5 col-md-6 col-sm-12 col-12 text-right mt-1">
        <%= f.submit '更新する', 
          class:"btn btn-primary"
        %>
      </div>
      
    </div>
  <% end %>
  <!--END ジャンル情報編集フォーム-->
  
  <!--登録済みジャンル画像表示-->
  <h5 class="mt-5">
    登録中のジャンルイメージ：
    <%= image_tag @genre.genre_image,
      size: "80x80", 
      class:"rounded-circle m-3" 
    %>
  </h5>
  
</div>

app/views/admin/genres/index.html.erb
<div class ="container">
  
  <h3 class="mb-3">
    ジャンル登録
  </h3>
  
  <!--START ジャンル登録フォーム-->
  <%= form_with model: @genre,url: admin_genres_path, method: :post do |f| %>
    <div class = "row g-3 mt-4 mx-auto">
      
      <!--ジャンル名入力-->
      <div class ="col-lg-10 col-md-12 col-sm-12 col-12 mt-1">
        <%= f.text_field :name, 
          placeholder:"ジャンル名", 
          class:"mr-2 form-control" 
        %>
      </div>
      
      <!--ジャンル画像添付-->
      <div class="col-lg-5 col-md-6 col-sm-12 col-12 mt-1">
        <%= f.file_field :genre_image %>
      </div>
      
      <!--登録ボタン-->
      <div class="col-lg-5 col-md-6 col-sm-12 col-12 text-right mt-1">
        <%= f.submit '登録する', 
          class:"btn btn-success" 
        %>
      </div>
    </div>
  <% end %>
  <!--END ジャンル登録フォーム-->

  
  <h3 class="mt-5 mb-3">ジャンル一覧</h3>
      
  <div class ="row">
    <div class ="col-lg-10 col-md-10 col-sm-12 col-10 table-responsive mb-5">  
      
      <!--START ジャンル一覧表-->
      <table class ="table table-bordered mx-auto">
        <thead>
          <tr>
            <th class="no-wrap">
              No.
            </th>
            <th class="no-wrap">
              ジャンル名・イメージ画像
            </th>
          </tr>
        </thead>
        
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <!--登録ID-->
              <td>
                <%= genre.id %>
              </td>
              
              <!--START ジャンル名、画像表示-->
              <td class="genre-preview no-wrap">
                <!--ジャンル名-->
                <%= genre.name %>
                <!--ジャンル画像-->
                <span class="no-wrap">
                  <%= image_tag genre.genre_image, 
                    size: "50x50", 
                    class:"rounded-circle ml-3" 
                  %>
                  <%= link_to '編集',
                    edit_admin_genre_path(genre.id), 
                    class:"btn btn-success ml-2" 
                  %>
                </span>
              </td>
              <!--END ジャンル名、画像表示-->
            </tr>
          <% end %>
        </tbody>
      </table>
      <!--END ジャンル一覧表-->
      
    </div>
  </div>
</div>