config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者ログイン画面
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
  # ユーザーログイン・新規登録画面
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ルートパス設定
  root to: "public/homes#top"

  # ゲストログイン
  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー画面のルーティング設定
  scope module: :public do
    # Homesコントローラ
    get "/about" => "homes#about", as: "about"

    # Recruitsコントローラ

    resources :recruits do
      # , :except => :destroy do
      patch "update_status" => "recruits#update_status", as: "update_status"
      # Likesコントローラ
      resource :likes, only: [:create, :destroy]
    end

    # Usersコントローラ
    # get "users/:id/edit" => "users#edit", as: "edit_user"
    # get "users/:id" => "users#show", as: "show_user"
    # patch "users/:id" => "users#update", as: "update_user"
    resources :users, only: [:edit, :show, :update] do
      get "my_page" => "users#my_page", as: "my_page"
      get "unsubscribe" => "users#unsubscribe_confirm", as: "unsubscribe_confirm"
      patch "unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      # Followsコントローラ
      resource :follows, only: [:create, :destroy]
    end

    # Entriesコントローラ
    resources :entries, only: [:index, :create, :show, :destroy, :update]

    # Notifiesコントローラ
    resources :notifies, only: :index

    # Sitesコントローラ
    resources :sites, only: [:index, :create, :destroy]

    # Messagesコントローラ
    resources :messages, only: :create

    # Roomsコントローラ
    resources :rooms, only: [:show, :create]
  end

  # 管理者画面のルーティング設定
  namespace :admin do
    # Homesコントローラ
    get "/" => "homes#top"

    # Genresコントローラ
    # get "/genres" => "genres#index"
    # post "/genres" => "genres#create"
    # get "/genres/:id/edit" => "genres#edit", as: "edit_genres"
    # patch "/genres/:id" =>"genres#update", as: "update_genres"
    resources :genres, only: [:index, :create, :edit, :update]

    # Uersコンロローラ
    # get "users/:id" => "users#show", as: "show_users"
    # get "users/:id/edit" => "users#edit", as: "edit_users"
    # patch "users/:id" => "users#update", as: "update_users"
    resources :users, only: [:show, :edit, :update]
  end
end

app/controllers/admin/homes_controller.rb
# frozen_string_literal: true

class Admin::HomesController < ApplicationController
  before_action :admin_only

  def top
    @users = User.all
  end

  private
    def user_params
      params.require(:user).permit(
        :club_name,
        :captain_last_name,
        :captain_first_name,
        :age_group,
        :genre_id,
        :prefecture,
        :municipality,
        :address,
        :introduction,
        :image,
        :email
      )
    end
end

app/views/admin/homes/top.html.erb
<div class ="container">
  <div class ="row">
    <h2>ユーザー一覧</h2>

    <div class ="col-lg-10 col-md-12 col-sm-12 col-12 mt-3 table-responsive mx-auto">
      <!--START ユーザー一覧表-->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="no-wrap">
              No.
            </th>
            
            <th class="no-wrap">
              クラブ名
            </th>
            
            <th class="no-wrap">
              代表者氏名
            </th>
            
            <th class="no-wrap">
              e-mail
            </th>
            
            <th class="no-wrap">
              活動ステータス
            </th>
            
          </tr>
        </thead>

        <% @users.each do |user| %>
          <tbody>
            <tr>
              <!--ユーザーID-->
              <td class="no-wrap">
                <%= user.id %>
              </td>
              
              <!--クラブ名-->
              <td class="no-wrap">
                <%= link_to admin_user_path(user.id), class:"text-dark link" do %>
                  <%= user.club_name %>
                <% end %>
              </td>
              
              <!--ユーザー名（クラブ代表名）-->
              <td class="no-wrap">
                <%= user.captain_name %>
              </td>
              
              <!--e-mail-->
              <td class="no-wrap">
                <%= user.email %>
              </td>
              
              <!--活動状況-->
              <td class="no-wrap">
                <%= active_status(user) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <!--END ユーザー一覧表-->
      
    </div>
  </div>
</div>