config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者ログイン画面
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
  # ユーザーログイン・新規登録画面
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # ルートパス設定
  root to: "public/homes#top"

  # ゲストログイン
  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー画面のルーティング設定
  scope module: :public do
    # Homesコントローラ
    get "/about" => "homes#about", as: "about"

    # Recruitsコントローラ

    resources :recruits do
      # , :except => :destroy do
      patch "update_status" => "recruits#update_status", as: "update_status"
      # Likesコントローラ
      resource :likes, only: [:create, :destroy]
    end

    # Usersコントローラ
    # get "users/:id/edit" => "users#edit", as: "edit_user"
    # get "users/:id" => "users#show", as: "show_user"
    # patch "users/:id" => "users#update", as: "update_user"
    resources :users, only: [:edit, :show, :update] do
      get "my_page" => "users#my_page", as: "my_page"
      get "unsubscribe" => "users#unsubscribe_confirm", as: "unsubscribe_confirm"
      patch "unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      # Followsコントローラ
      resource :follows, only: [:create, :destroy]
    end

    # Entriesコントローラ
    resources :entries, only: [:index, :create, :show, :destroy, :update]

    # Notifiesコントローラ
    resources :notifies, only: :index

    # Sitesコントローラ
    resources :sites, only: [:index, :create, :destroy]

    # Messagesコントローラ
    resources :messages, only: :create

    # Roomsコントローラ
    resources :rooms, only: [:show, :create]
  end

  # 管理者画面のルーティング設定
  namespace :admin do
    # Homesコントローラ
    get "/" => "homes#top"

    # Genresコントローラ
    # get "/genres" => "genres#index"
    # post "/genres" => "genres#create"
    # get "/genres/:id/edit" => "genres#edit", as: "edit_genres"
    # patch "/genres/:id" =>"genres#update", as: "update_genres"
    resources :genres, only: [:index, :create, :edit, :update]

    # Uersコンロローラ
    # get "users/:id" => "users#show", as: "show_users"
    # get "users/:id/edit" => "users#edit", as: "edit_users"
    # patch "users/:id" => "users#update", as: "update_users"
    resources :users, only: [:show, :edit, :update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>
      ClubMatch
    </title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="d-flex flex-column vh-100">
    
    <!--START　ヘッダー-->
    <header>
      <nav class ="navbar navbar-expand-lg navbar-light">
        <div class ="container mt-0">
        
          <!--START　ロゴ-->
          <div class ="navbar-brand ">
            
            <!--管理者権限でログイン時表示-->
            <% if admin_signed_in? %>
            
              <%= link_to admin_path do %>
                <%= image_tag'club_match_logo.png',
                  :size => '125x125' 
                %>
              <% end %>
            
            <!--一般ユーザーログイン時に表示-->
            <% else %>
            
              <%= link_to root_path do %>
                <%= image_tag'club_match_logo.png',
                  :size => '125x125' 
                %>
              <% end %>
              
            <% end %>
          </div>
          <!--END　ロゴ-->

          <!--START 画面幅縮小時のトグルボタン-->
          <button 
            class="navbar-toggler" 
            type="button" 
            data-toggle="collapse" 
            data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" 
            aria-expanded="false" 
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <!--END 画面幅縮小時のトグルボタン-->

          <div class ="collapse navbar-collapse" id="navbarNavDropdown">
            
            <!--START　ユーザーログイン後のヘッダー-->
            <% if user_signed_in? %>
              <small>
                <%= current_user.club_name %>さん、ようこそ！
              </small>
              
              <ul class ="navbar-nav ml-auto">
                
                <!--応募履歴リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to '応募履歴', 
                    entries_path,
                    class:"btn btn-warning btn-gradient py-2 w-100 no-wrap" 
                  %>
                </li>
                
                <!--募集画面リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to '募集する', 
                    new_recruit_path,
                    class:"btn btn-warning btn-gradient py-2 w-100  no-wrap" 
                  %>
                </li>
                
                <!--マイページリンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to 'マイページ', 
                    user_my_page_path(current_user.id),
                    class:"btn btn-warning btn-gradient py-2 w-100 no-wrap"
                  %>
                </li>
                
                <!--ログアウトボタン-->
                <li class ="nav-item">
                  <%= link_to 'ログアウト', 
                    destroy_user_session_path, 
                    method: :delete,
                    class:"btn btn-warning btn-gradient py-2 w-100  no-wrap" 
                  %>
                </li>
                
              </ul>
            <!--END ユーザーログイン後のヘッダー-->

            <!--START 管理者ログイン後のヘッダー-->
            <% elsif admin_signed_in? %>
            
              <ul class ="navbar-nav ml-auto">
                
                <!--ジャンル管理リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to 'ジャンル管理', 
                    admin_genres_path,
                    class:"btn btn-warning btn-gradient w-100 py-2 no-wrap"
                  %>
                </li>
                
                <!--ユーザー一覧リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to 'ユーザー一覧', 
                    admin_path,
                    class:"btn btn-warning btn-gradient w-100 py-2 no-wrap"
                  %>
                </li>
                
                <!--ログアウトリンク-->
                <li class ="nav-item">
                  <%= link_to 'ログアウト', 
                    destroy_admin_session_path,
                    method: :delete, 
                    class:"btn btn-warning btn-gradient w-100 py-2 no-wrap" 
                  %>
                </li>
                
              </ul>
            <!--END 管理者ログイン後のヘッダー-->

            <!--START ログアウト後(サインイン前)のヘッダー-->
            <% else %>
            
              <ul class ="navbar-nav ml-auto">
                
                <!--募集一覧リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to '募集一覧', 
                    recruits_path,
                    class:"btn btn-warning btn-gradient w-100 py-2 no-wrap"
                  %>
                </li>
                
                <!--新規登録リンク-->
                <li class ="nav-item mr-3 mb-1">
                  <%= link_to '新規登録', 
                    new_user_registration_path,
                    class: "btn btn-warning btn-gradient w-100 py-2 no-wrap"
                  %>
                </li>
                
                <!--ログインリンク-->
                <li class ="nav-item">
                  <%= link_to 'ログイン', 
                    new_user_session_path,
                    class:"btn btn-warning btn-gradient w-100 py-2 no-wrap"
                  %>
                </li>
                
              </ul>
            <% end %>
            <!--END ログアウト後のヘッダー-->
            
          </div>
        </div>
      </nav>
    </header>
    <!--END　ヘッダー-->

    <main class="mb-auto">
      <%= yield %>
    </main>
    <%#= debug(params) if Rails.env.development? %>
    
    <!--START フッター-->
    <footer class="footer">
      <div class="bg-warning bg-gradient p-2">
        
        <p class="text-light text-center m-0">
          ClubMatch
        </p>
        
      </div>
    </footer>
    <!--END フッター-->
    
  </body>
</html>